sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t davidgibbsig/alpine-glibc .

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push davidgibbsig/alpine-glibc 