#!/usr/bin/env ash

set -ex

main() {
  RSA_FILE=$(ls /home/builder/.abuild/${PACKAGER}-*.rsa | head -n 1)
  export PACKAGER_PRIVKEY="$RSA_FILE"

  mkdir -p "$REPODEST" /home/builder/.abuild
  abuild-apk update
  [ "$RSA_PRIVATE_KEY" ] && {
    echo -e "$RSA_PRIVATE_KEY" >"/home/builder/.abuild/$RSA_PRIVATE_KEY_NAME"
    export PACKAGER_PRIVKEY="/home/builder/.abuild/$RSA_PRIVATE_KEY_NAME"
  }
  sudo chown -R builder:abuild /home/builder/package
  sudo chown -R builder:abuild $REPODEST

  exec abuild "$@"
}

main "$@"
